services:
  database:
    image: mongo
    ports:
      - 27017-27019:27017-27019
    logging:
      driver: 'none'
    command: mongod --quiet --logpath /dev/null
  application:
    image: node:20-bullseye
    command: sh -c "npm install && npm start"
    working_dir: /usr/src/api/
    volumes:
      - ./:/usr/src/api/
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - DEBUG=true
      - NODE_ENV=${NODE_ENV:-development}
    env_file:
      - .env
    depends_on:
      - database
