version: '3.7'

services:
  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: eem9Phi1zeu3Eo6fai0r
      MARIADB_DATABASE: worlddriven
      MARIADB_USER: worlddriven
      MARIADB_PASSWORD: zu8uSiuxohviePh8ohmi
    ports:
      - 3306:3306
  application:
    image: node:16.13-bullseye
    command: npm start
    working_dir: /usr/src/api/
    volumes:
      - ./:/usr/src/api/
    ports:
      - ${PORT:-3000}:3000
    environment:
      - DEBUG=true
      - JAWSDB_MARIA_URL=mysql://worlddriven:zu8uSiuxohviePh8ohmi@database:3306/worlddriven
      - PORT=3000
    env_file:
      - .env
    depends_on:
      - database
