version: 2
jobs:
  test:
    docker:
      - image: cimg/node:20.17
        environment:
          MONGO_URL: mongodb://127.0.0.1:27017/worlddriven_test
      - image: mongo:7.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run build
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
