version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7-stretch-node
        environment:
          JAWSDB_MARIA_URL: mysql://worlddriven:password@127.0.0.1/worlddriven
      - image: circleci/mariadb:latest
        environment:
          MYSQL_USER: worlddriven
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: worlddriven
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run build
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
